---

- hosts: web

  tasks:
  - name: Installation de Apache sur Redhat Family
    dnf:
     name: httpd
     state: present
     
    when: ansible_facts['os_family'] == "RedHat"
  - name: Installation du serveur sur du Debian
    apt:
     name: apache2
     state: present
    when: ansible_facts['os_family'] == "Debian"
