---
- hosts: localhost
  tasks:
  - name: Creation du groupe admin
    group: 
     name: admin
     state: present

  - name: Creation d'un user ansible
    user:
     name: ansible
     state: present
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: .ssh/id_rsa
     password: 'root'
     group: 'admin'
     
- hosts: web 
  tasks:
  - name: Creation du groupe admin
    group:
     name: admin
     state: present

  - name: Creation d'un user ansible
    user:
     name: ansible
     state: present
     password: 'root'
     group: 'admin'

  - name: Ajout de la clef publique du User ansible
    authorized_key:
     user: ansible
     state: present
     key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

  - name: Déplacer le fichier Sudoers vers le serveur
    copy:
     src: ./ansible.sudo
     dest: /etc/sudoers.d/ansible
    
